<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ad" nsURI="agl.allpattern.ad" nsPrefix="agl.allpattern.ad">
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitynode" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass10"/>
</ecore:EPackage>
